name: graphviz
version: 0.0.10
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Emscripten module for Graphviz
homepage: https://github.com/rwl/graphviz.dart
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  emscripten: '>=0.0.2 <0.1.0'
  json_rpc_2: any
  protobuf: any
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
transformers:
- $dart2js:
    commandLineOptions:
    - --enable-enum
